kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: argo-chaos
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: reviews
  mode: random
  action: pod-kill
  gracePeriod: 50
